version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "therootpass1234"
      TZ: "Europe/Copenhagen"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./scripts/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/mysql:/var/lib/mysql
